Repository fink/fink-distributions, pull requests merged in 2018-04, with the labels that each got.

#78 neon27: new version, that supports openssl110; -I ordering fixes
  10.9-libcxx/stable/main/finkinfo/libs/neon27.info
  10.9-libcxx/stable/main/finkinfo/libs/neon27.patch
Labels: waiting for reply

#73 rcs: standard 10.13 fix for gnulib vasnprintf
  10.9-libcxx/stable/main/finkinfo/devel/rcs.info
  10.9-libcxx/stable/main/finkinfo/devel/rcs.patch
Labels: waiting for reply

#116 pil-py: Install headers #included by own Imaging.h.
  10.9-libcxx/stable/main/finkinfo/graphics/pil-py.info
Labels: bug, waiting for reply

#128 Update perlmods
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/algorithm-permute-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/cgi-simple-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/class-load-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/class-load-xs-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/devel-checkos-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/devel-declare-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/event-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/file-fcntllock-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/gnome2-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/hash-util-fieldhash-compat-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/http-parser-xs-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/indirect-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/json-dwiw-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/module-starter-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/net-server-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/parent-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/parse-recdescent-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/pathtools-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/perl6-slurp-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/perlio-eol-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/pod-pom-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/pod-pom-pm.patch
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/proc-processtable-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/ref-util-xs-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/rrd-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/scope-guard-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/scope-upper-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/set-object-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/shout2-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/sort-key-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/statistics-basic-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/string-escape-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/tcl-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/term-readline-gnu-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/threads-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/unicode-string-pm.info
Labels: submissions

#130 Pylint update (including dependencies for py36)
  10.9-libcxx/stable/main/finkinfo/devel/astroid-py.info
  10.9-libcxx/stable/main/finkinfo/devel/pylint-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/isort-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/lazy-object-proxy-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/wrapt-py.info
Labels: enhancement, submissions
