Repository fink/fink-distributions, pull requests merged in 2019-04, with the labels that each got.

#378 jbig2dec 0.15 (retrieve from GitHub releases page)
  10.7/stable/main/finkinfo/graphics/jbig2dec.info
  10.9-libcxx/stable/main/finkinfo/graphics/jbig2dec.info
Labels: new upstream

#276 zmq-py, libzmq6: update, add py37 variant
  10.9-libcxx/stable/main/finkinfo/net/libzmq6-shlibs.info
  10.9-libcxx/stable/main/finkinfo/net/zmq-py.info
Labels: enhancement

#210 peakutils-py: new python lib for peak fitting.
  10.9-libcxx/stable/main/finkinfo/sci/peakutils-py.info
Labels: new package

#404 Use a custom mirror to search all sodium source locations.
  10.9-libcxx/stable/main/finkinfo/crypto/libsodium13.info
  10.9-libcxx/stable/main/finkinfo/crypto/libsodium17.info
  10.9-libcxx/stable/main/finkinfo/crypto/libsodium23.info
Labels: source moved
