Repository fink/fink-distributions, pull requests merged in 2019-05, with the labels that each got.

#400 New cyrus-sasl upstream version
  10.9-libcxx/stable/main/finkinfo/net/cyrus-sasl2.3.info
Labels: new upstream, source moved

#408 Leftover fixes to django-localflavor-py tests and semanticversion-py BuildDepends
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/semanticversion-py.info
  10.9-libcxx/stable/main/finkinfo/web/django-localflavor-py.info
Labels: bug, missing (build) dependency

#391 Ipython 5+ and Notebook Depends
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/appnope-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/backcall-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/backports.shutil-get-terminal-size-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/bleach-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/entrypoints-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/ipython-genutils-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jdcal-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jedi-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/nose-warnings-filters-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pandocfilters-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/parso-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pickleshare-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/prometheus-client-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/prompt-toolkit-py-1.0.15.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/prompt-toolkit-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pygraphviz-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/send2trash-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/testpath-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/traitlets-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/wcwidth-py.info
  10.9-libcxx/stable/main/finkinfo/web/selenium-py.info
  10.9-libcxx/stable/main/finkinfo/web/zopeevent-py.info
  10.9-libcxx/stable/main/finkinfo/web/zopeinterface-py.info
Labels: missing (build) dependency, new package

#412 psutil-py update to 5.6.2 and fixed build/install
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/psutil-py-0001-dont-depend-on-install-when-running-tests.patch
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/psutil-py-0002-pass-PYTHONPATH-to-the-test-runner.patch
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/psutil-py.info
Labels: bug, new upstream

#385 Scipy update to 1.2.1 and Python 3.7 built against new OpenBLAS package
  10.9-libcxx/stable/main/finkinfo/sci/openblas.info
  10.9-libcxx/stable/main/finkinfo/sci/openblas.patch
  10.9-libcxx/stable/main/finkinfo/sci/scipy-py.info
Labels: enhancement, new package

#410 pycodestyle 2.5.0
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pycodestyle-py.info
Labels: new upstream
