Repository fink/fink-distributions, pull requests merged in 2019-11, with the labels that each got.

#488 Update pgplot.info
  10.9-libcxx/stable/main/finkinfo/sci/pgplot.info
Labels: enhancement

#492 lazarus: Update to upstream version 2.0.6
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-doc.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-carbon.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa-32bit.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-cocoa.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-gtk2.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt4.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-qt5.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win32.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-win64.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-arm.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus-lcl-wince-i386.info
  10.9-libcxx/stable/main/finkinfo/devel/lazarus.info
Labels: enhancement, new upstream

#503 xtide upstream version 2.15.2 and harmonics 20190620
  10.9-libcxx/stable/main/finkinfo/sci/xtide-harmonics-us.info
  10.9-libcxx/stable/main/finkinfo/sci/xtide.info
Labels: new upstream

#520 New package postgresql12 12.1
  10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql12.patch
Labels: new package

#522 nettle7-shlibs 3.5.1 - updated Debian patchfile
  10.9-libcxx/stable/main/finkinfo/crypto/nettle7-shlibs.info
Labels: bug
