Repository fink/fink-distributions, pull requests merged in 2019-10, with the labels that each got.

#479 Gnutls30 update
  10.9-libcxx/stable/main/finkinfo/crypto/gnutls-2.12-shlibs.info
  10.9-libcxx/stable/main/finkinfo/crypto/gnutls30-shlibs.info
Labels: new package, new upstream, submissions

#480 sdl2 v2.0.10
  10.9-libcxx/stable/main/finkinfo/games/sdl2.info
Labels: new upstream

#487 Update ortep3.info
  10.9-libcxx/stable/main/finkinfo/sci/ortep3.info
Labels: enhancement

#485 Update gfortran programs to gcc9
  10.9-libcxx/stable/main/finkinfo/devel/floppy.info
  10.9-libcxx/stable/main/finkinfo/devel/flow.info
  10.9-libcxx/stable/main/finkinfo/devel/ftidy.info
  10.9-libcxx/stable/main/finkinfo/devel/snoopy.info
  10.9-libcxx/stable/main/finkinfo/devel/to-f90.info
  10.9-libcxx/stable/main/finkinfo/sci/freehelix.info
  10.9-libcxx/stable/main/finkinfo/sci/ifeffit.info
Labels: enhancement
