Repository fink/fink-distributions, pull requests merged in 2020-03, with the labels that each got.

#571 Add missing dependency on help2man
  10.9-libcxx/stable/main/finkinfo/devel/libtool2.info
Labels: bug, missing (build) dependency, waiting for owner

#580 Fix assumptions from internal time::local about 2-digit years.
  10.9-libcxx/stable/main/finkinfo/languages/perl5162-timelocal-y2020.patch
  10.9-libcxx/stable/main/finkinfo/languages/perl5162.info
  10.9-libcxx/stable/main/finkinfo/languages/perl5182-timelocal-y2020.patch
  10.9-libcxx/stable/main/finkinfo/languages/perl5182.info
  10.9-libcxx/stable/main/finkinfo/languages/perl5184-timelocal-y2020.patch
  10.9-libcxx/stable/main/finkinfo/languages/perl5184.info
  10.9-libcxx/stable/main/finkinfo/text/texi2html-perl5162-timelocal-y2020.patch
  10.9-libcxx/stable/main/finkinfo/text/texi2html-perl5162.info
Labels: bug

#577 OpenBLAS updated to 0.3.8 and fixed smallscaling build on 10.11 and lower
  10.9-libcxx/stable/main/finkinfo/sci/openblas.info
  10.9-libcxx/stable/main/finkinfo/sci/openblas.patch
Labels: bug, new upstream

#574 Fix exuberant-ctags build on 10.14 with __unused macro issues.
  10.9-libcxx/stable/main/finkinfo/editors/exuberant-ctags.info
  10.9-libcxx/stable/main/finkinfo/editors/exuberant-ctags_unused_namespace.patch
Labels: bug, waiting for owner
