Repository fink/fink-distributions, pull requests merged in 2020-01, with the labels that each got.

#553 Crypt::OpenSSL::* updates
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/crypt-openssl-bignum-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/crypt-openssl-bignum-pm.patch
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/crypt-openssl-random-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/crypt-openssl-random-pm.patch
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/crypt-openssl-rsa-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/crypt-openssl-rsa-pm.patch
Labels: waiting for owner

#548 update audiofile dependees
  10.9-libcxx/stable/main/finkinfo/gnome/gst-plugins-good-0.10.info
  10.9-libcxx/stable/main/finkinfo/gnome/libgnome2.info
  10.9-libcxx/stable/main/finkinfo/gnome/potamus.info
  10.9-libcxx/stable/main/finkinfo/gnome/potamus.patch
  10.9-libcxx/stable/main/finkinfo/libs/audiofile-shlibs.info
  10.9-libcxx/stable/main/finkinfo/libs/audiofile.info
  10.9-libcxx/stable/main/finkinfo/libs/libxine1.info
  10.9-libcxx/stable/main/finkinfo/libs/libxine2.info
  10.9-libcxx/stable/main/finkinfo/libs/libxine2.patch
  10.9-libcxx/stable/main/finkinfo/sound/esound.info
  10.9-libcxx/stable/main/finkinfo/sound/mpd.info
  10.9-libcxx/stable/main/finkinfo/sound/normalize.info
Labels: new upstream

#529 OpenBLAS migrated to gcc9 and update to upstream 0.3.7
  10.9-libcxx/stable/main/finkinfo/sci/openblas.info
  10.9-libcxx/stable/main/finkinfo/sci/openblas.patch
Labels: enhancement, new upstream

#555 cmake: new version
  10.9-libcxx/stable/main/finkinfo/devel/cmake.info
Labels: new upstream

#542 Updated sdl2 with patch for 10.11 systems.
  10.9-libcxx/stable/main/finkinfo/games/sdl2.info
  10.9-libcxx/stable/main/finkinfo/games/sdl2.patch
Labels: bug, waiting for owner

#547 pandas-py 0.25.3
  10.9-libcxx/stable/main/finkinfo/sci/pandas-py-0.19.2.info
  10.9-libcxx/stable/main/finkinfo/sci/pandas-py.info
Labels: new upstream

#528 ESS update to 18.10.2 + emacs26 compatibility
  10.9-libcxx/stable/main/finkinfo/editors/ess.info
Labels: enhancement, new upstream

#564 Atlas 3.10.3
  10.9-libcxx/stable/main/finkinfo/sci/atlas-xcode7.patch
  10.9-libcxx/stable/main/finkinfo/sci/atlas.info
Labels: new upstream

#496 migrate mommsen packages to gcc9
  10.9-libcxx/stable/main/finkinfo/sci/cernlib2006.info
  10.9-libcxx/stable/main/finkinfo/sci/geant4.9.info
  10.9-libcxx/stable/main/finkinfo/sci/patchy4.info
  10.9-libcxx/stable/main/finkinfo/sci/root-pythia.info
  10.9-libcxx/stable/main/finkinfo/sci/root5.info
  10.9-libcxx/stable/main/finkinfo/sci/root5.patch
  10.9-libcxx/stable/main/finkinfo/sci/xrootd4.info
Labels: new upstream
