Repository fink/fink-distributions, pull requests merged in 2020-02, with the labels that each got.

#515 SDL2 versions of sdl-image, sdl-mixer, and sdl-ttf
  10.9-libcxx/stable/main/finkinfo/games/sdl2-image.info
  10.9-libcxx/stable/main/finkinfo/games/sdl2-mixer.info
  10.9-libcxx/stable/main/finkinfo/games/sdl2-ttf.info
Labels: new package, waiting for owner

#575 Re-enable cups on 10.15 and unify .info files
  10.9-libcxx/stable/main/finkinfo/gnome/gtk+2-10.15.info
  10.9-libcxx/stable/main/finkinfo/gnome/gtk+2-cups.patch
  10.9-libcxx/stable/main/finkinfo/gnome/gtk+2.info
Labels: bug

#578 Added support for pip installed for python v3.8
  10.9-libcxx/stable/main/finkinfo/languages/pip-py.info
Labels: new package
