Repository fink/fink-distributions, pull requests merged in 2020-07, with the labels that each got.

#635 build cleanup for PyQt5
  10.9-libcxx/stable/main/finkinfo/languages/pyqt5-mac-py.info
Labels: bug

#644 Rtmpdump update to v2.4
  10.9-libcxx/stable/main/finkinfo/net/librtmp1-shlibs.info
  10.9-libcxx/stable/main/finkinfo/net/librtmp1-shlibs.patch
  10.9-libcxx/stable/main/finkinfo/net/rtmpdump.info
Labels: new package, new upstream

#641 OpenBLAS update to 0.3.10 and new fix for missing CLOCK_REALTIME
  10.9-libcxx/stable/main/finkinfo/sci/openblas.info
  10.9-libcxx/stable/main/finkinfo/sci/openblas.patch
Labels: bug, new upstream

#649 f-p-p: search for Xcode's otool-classic before falling back to /usr/bin/otool
  10.9-libcxx/stable/main/finkinfo/devel/fink-package-precedence.info
  10.9-libcxx/stable/main/finkinfo/devel/fink-package-precedence.patch
Labels: bug
