Repository fink/fink-distributions, pull requests merged in 2020-05, with the labels that each got.

#604 proper detection of clang-v11 from Xcode 11.4 (python)
  10.9-libcxx/stable/main/finkinfo/languages/python27.info
  10.9-libcxx/stable/main/finkinfo/languages/python27.patch
  10.9-libcxx/stable/main/finkinfo/languages/python34.info
  10.9-libcxx/stable/main/finkinfo/languages/python34.patch
  10.9-libcxx/stable/main/finkinfo/languages/python35.info
  10.9-libcxx/stable/main/finkinfo/languages/python35.patch
  10.9-libcxx/stable/main/finkinfo/languages/python36.info
  10.9-libcxx/stable/main/finkinfo/languages/python36.patch
  10.9-libcxx/stable/main/finkinfo/languages/python37.info
  10.9-libcxx/stable/main/finkinfo/languages/python37.patch
Labels: bug, waiting for owner

#599 GnuTLS 3.6.13
  10.9-libcxx/stable/main/finkinfo/crypto/gnutls30-shlibs.info
  10.9-libcxx/stable/main/finkinfo/crypto/gnutls30-xcode11.4.patch
Labels: bug, new upstream

#562 xmlsec: new version (new -shlibs name)
  10.9-libcxx/stable/main/finkinfo/crypto/xmlsec-shlibs.info
  10.9-libcxx/stable/main/finkinfo/crypto/xmlsec-shlibs.patch
  10.9-libcxx/stable/main/finkinfo/crypto/xmlsec1-shlibs.info
  10.9-libcxx/stable/main/finkinfo/crypto/xmlsec1-shlibs.patch
Labels: new upstream, waiting for reply

#605 Update pysvn to 1.9.11 for svn19 1.13 compatibility and add py38 variant
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/pysvn-py.info
Labels: bug, new upstream

#589 Ruby updates
  10.9-libcxx/stable/main/finkinfo/languages/ruby24.info
  10.9-libcxx/stable/main/finkinfo/languages/ruby24.patch
  10.9-libcxx/stable/main/finkinfo/languages/ruby25.info
  10.9-libcxx/stable/main/finkinfo/languages/ruby26.info
Labels: new upstream, waiting for owner
