Repository fink/fink-distributions, pull requests merged in 2020-09, with the labels that each got.

#658 relax: bump all possible dependencies.
  10.9-libcxx/stable/main/finkinfo/sci/relax.info
Labels: enhancement, waiting for owner

#659 Move H5api_adpt.h header into main -dev package to match hdf5.100.v* …
  10.9-libcxx/stable/main/finkinfo/sci/hdf5.10-oldapi.info
  10.9-libcxx/stable/main/finkinfo/sci/hdf5.10.info
Labels: bug

#663 PostgreSQL upstream updates August 2020
  10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql96.info
Labels: new upstream
