Repository fink/fink-distributions, pull requests merged in 2020-12, with the labels that each got.

#115 libdbi upgrade
  10.9-libcxx/stable/main/finkinfo/database/libdbi-drivers-mysql.info
  10.9-libcxx/stable/main/finkinfo/database/libdbi-drivers-pgsql.info
  10.9-libcxx/stable/main/finkinfo/database/libdbi-drivers-pgsql94.info
  10.9-libcxx/stable/main/finkinfo/database/libdbi-drivers-sqlite3.info
  10.9-libcxx/stable/main/finkinfo/database/libdbi-shlibs.info
  10.9-libcxx/stable/main/finkinfo/database/libdbi1-shlibs.info
Labels: new package, new upstream, waiting for reply

#697 gdal2 2.4.4 - new upstream
  10.9-libcxx/stable/main/finkinfo/libs/gdal2.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/gdal-py.info
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/gdal-py.patch
Labels: new upstream

#709 cmake 3.19.1 - new upstream
  10.9-libcxx/stable/main/finkinfo/devel/cmake.info
Labels: new upstream

#710 Libgeotiff2 update
  10.9-libcxx/stable/main/finkinfo/graphics/libgeotiff2.info
Labels: new upstream

#620 XEphem fixes for Guide Star Catalogue and other downloads
  10.9-libcxx/stable/main/finkinfo/sci/xephem.info
  10.9-libcxx/stable/main/finkinfo/sci/xephem.patch
Labels: bug, enhancement

#511 Building git-lfs using fink gnumake 4.2.1
  10.9-libcxx/stable/main/finkinfo/devel/git-lfs.info
  10.9-libcxx/stable/main/finkinfo/devel/git-lfs.patch
Labels: new upstream, waiting for owner

#561 migrate wgscott packages to gcc9
  10.9-libcxx/stable/main/finkinfo/sci/clipper.info
  10.9-libcxx/stable/main/finkinfo/sci/coot.info
  10.9-libcxx/stable/main/finkinfo/sci/libccp4.info
  10.9-libcxx/stable/main/finkinfo/sci/phaser-mpi.info
  10.9-libcxx/stable/main/finkinfo/sci/refmac.info
  10.9-libcxx/stable/main/finkinfo/sci/refmac.patch
  10.9-libcxx/stable/main/finkinfo/sci/tinker.info
  10.9-libcxx/stable/main/finkinfo/sci/usf.info
Labels: waiting for owner

#531 libnc-dap3: gcc upgrade, resolve some warnings, etc
  10.9-libcxx/stable/main/finkinfo/sci/libnc-dap3.info
  10.9-libcxx/stable/main/finkinfo/sci/libnc-dap3.patch
Labels: waiting for owner

#676 Fixed asn1crypto DocFiles for case-sensitive FS, update to 1.4
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/asn1crypto-py.info
Labels: bug, new upstream, waiting for owner

#694 udunits2 2.2.28 - new upstream
  10.9-libcxx/stable/main/finkinfo/sci/udunits2.info
Labels: new upstream
