Repository fink/fink-distributions, pull requests merged in 2020-06, with the labels that each got.

#632 Update openblas to upstream 0.3.9 and gcc10
  10.9-libcxx/stable/main/finkinfo/sci/openblas.info
  10.9-libcxx/stable/main/finkinfo/sci/openblas.patch
Labels: new upstream

#540 ENH: Python3 updates and test suite fixes
  10.9-libcxx/stable/main/finkinfo/languages/python27.info
  10.9-libcxx/stable/main/finkinfo/languages/python27.patch
  10.9-libcxx/stable/main/finkinfo/languages/python34.info
  10.9-libcxx/stable/main/finkinfo/languages/python35.info
  10.9-libcxx/stable/main/finkinfo/languages/python36.info
  10.9-libcxx/stable/main/finkinfo/languages/python37.info
  10.9-libcxx/stable/main/finkinfo/languages/python38.info
  10.9-libcxx/stable/main/finkinfo/languages/python38.patch
Labels: bug, new upstream

#634 Fix build failure linking id3lib library on 10.15 by modernizing autotools components
  10.9-libcxx/stable/main/finkinfo/libs/id3lib4.info
  10.9-libcxx/stable/main/finkinfo/libs/id3lib4.patch
Labels: bug

#607 alpine: new upstream
  10.9-libcxx/stable/main/finkinfo/net/alpine.info
  10.9-libcxx/stable/main/finkinfo/net/alpine.patch
Labels: new upstream
