Repository fink/fink-distributions, pull requests merged in 2021-01, with the labels that each got.

#125 Scribus upgrade
  10.9-libcxx/stable/main/finkinfo/text/scribus-aqua.info
  10.9-libcxx/stable/main/finkinfo/text/scribus-x11.info
  10.9-libcxx/stable/main/finkinfo/text/scribus.patch
Labels: new upstream

#708 Cppunit upgrade
  10.9-libcxx/stable/main/finkinfo/libs/libe-book01-dev.info
  10.9-libcxx/stable/main/finkinfo/libs/libepubgen0.info
  10.9-libcxx/stable/main/finkinfo/libs/librvngabw0.info
Labels: new upstream, submissions

#715 new version: mupdf
  10.9-libcxx/stable/main/finkinfo/text/mupdf.info
  10.9-libcxx/stable/main/finkinfo/text/mupdf.patch
Labels: waiting for owner

#728 nmap: New upstream.
  10.9-libcxx/stable/main/finkinfo/net/nmap.info
Labels: new upstream

#732 Postgresql updates
  10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql94-implicit-declarations.patch
  10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql95-implicit-declarations.patch
  10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql96-implicit-declarations.patch
  10.9-libcxx/stable/main/finkinfo/database/postgresql96.info
Labels: bug, new upstream
