Repository fink/fink-distributions, pull requests merged in 2021-06, with the labels that each got.

#768 freeciv: new version, dep upgrades
  10.9-libcxx/stable/main/finkinfo/games/freeciv.info
  10.9-libcxx/stable/main/finkinfo/games/freeciv.patch
Labels: new upstream, waiting for owner

#769 Autotrace update
  10.9-libcxx/stable/main/finkinfo/graphics/autotrace-shlibs.info
  10.9-libcxx/stable/main/finkinfo/graphics/autotrace-shlibs.patch
  10.9-libcxx/stable/main/finkinfo/graphics/autotrace3-shlibs.info
  10.9-libcxx/stable/main/finkinfo/graphics/autotrace3-shlibs.patch
  10.9-libcxx/stable/main/finkinfo/graphics/libmagickcore6.9.q16.2-shlibs.info
  10.9-libcxx/stable/main/finkinfo/graphics/libmagickcore7.q16.9-shlibs.info
Labels: waiting for owner

#763 pasdoc: update to upstream version 0.16.0
  10.9-libcxx/stable/main/finkinfo/devel/pasdoc-gui.info
  10.9-libcxx/stable/main/finkinfo/devel/pasdoc.info
Labels: new upstream
