Repository fink/fink-distributions, pull requests merged in 2021-04, with the labels that each got.

#757 gifsicle: update to upstream version 1.92
  10.9-libcxx/stable/main/finkinfo/graphics/gifsicle.info
Labels: new upstream

#758 unrar: update to upstream version 6.0.4
  10.9-libcxx/stable/main/finkinfo/utils/unrar.info
Labels: new upstream

#759 memtester: update to upstream version 4.5.0
  10.9-libcxx/stable/main/finkinfo/utils/memtester.info
Labels: new upstream

#777 g3: upstream patches to enable HEIF
  10.9-libcxx/stable/main/finkinfo/graphics/gd3-heif.patch
  10.9-libcxx/stable/main/finkinfo/graphics/gd3.info
Labels: bug

#653 flex-devel update to 2.6.4 and PDF doc build
  10.9-libcxx/stable/main/finkinfo/devel/flex-devel.info
Labels: enhancement, help wanted, new upstream
