Repository fink/fink-distributions, pull requests merged in 2021-05, with the labels that each got.

#781 flex transition
  10.9-libcxx/stable/main/finkinfo/devel/automake1.14.info
  10.9-libcxx/stable/main/finkinfo/devel/automake1.15.info
  10.9-libcxx/stable/main/finkinfo/devel/flex-devel.info
  10.9-libcxx/stable/main/finkinfo/devel/flex-legacy.info
  10.9-libcxx/stable/main/finkinfo/devel/flex.info
  10.9-libcxx/stable/main/finkinfo/gnome/gstreamer-0.10.info
  10.9-libcxx/stable/main/finkinfo/kde/kdelibs4.info
  10.9-libcxx/stable/main/finkinfo/languages/iverilog-snapshot.info
  10.9-libcxx/stable/main/finkinfo/libs/librasqal3-shlibs-10.14.5.info
  10.9-libcxx/stable/main/finkinfo/libs/librasqal3-shlibs-10.15.info
  10.9-libcxx/stable/main/finkinfo/libs/librasqal3-shlibs-10.9.info
  10.9-libcxx/stable/main/finkinfo/libs/librasqal3-shlibs.info
  10.9-libcxx/stable/main/finkinfo/sci/ginac2.info
  10.9-libcxx/stable/main/finkinfo/sci/mira.info
  10.9-libcxx/stable/main/finkinfo/sci/qepcad.info
  10.9-libcxx/stable/main/finkinfo/web/virtuoso.info
  10.9-libcxx/stable/main/finkinfo/x11-wm/amiwm.info
  10.9-libcxx/stable/main/finkinfo/x11/wine-32bit.info
Labels: new package

#791 io-compress update
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/compress-raw-bzip2-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/compress-raw-lzma-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/compress-raw-zlib-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/io-compress-lzf-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/io-compress-lzma-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/io-compress-lzop-pm.info
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/io-compress-pm.info
Labels: new upstream

#770 cernlib2006: fix FTBFS: no bin/makedepend or libXp.dylib in xquartz-2.8.0
  10.9-libcxx/stable/main/finkinfo/sci/cernlib2006.info
Labels: waiting for owner

#772 grace: updates for Xcode12
  10.9-libcxx/stable/main/finkinfo/sci/grace-implicit-declarations.patch
  10.9-libcxx/stable/main/finkinfo/sci/grace.info
Labels: bug, waiting for owner

#796 build fixes and cleanup for r-base3[3-6]
  10.9-libcxx/stable/main/finkinfo/sci/r-base33.info
  10.9-libcxx/stable/main/finkinfo/sci/r-base34.info
  10.9-libcxx/stable/main/finkinfo/sci/r-base35.info
  10.9-libcxx/stable/main/finkinfo/sci/r-base36-implicit-declarations.patch
  10.9-libcxx/stable/main/finkinfo/sci/r-base36.info
Labels: bug

#790 New pkg perl5302 to match system-perl on 11.3
  10.9-libcxx/stable/main/finkinfo/languages/perl5302-libperl-t.patch
  10.9-libcxx/stable/main/finkinfo/languages/perl5302-macos11.patch
  10.9-libcxx/stable/main/finkinfo/languages/perl5302-timehires.patch
  10.9-libcxx/stable/main/finkinfo/languages/perl5302.info
  10.9-libcxx/stable/main/finkinfo/languages/perl5302.patch
Labels: new upstream
