Repository fink/fink-distributions, pull requests merged in 2021-07, with the labels that each got.

#832 Update expat1 to fix Billion Laughs vulnerability
  10.9-libcxx/stable/main/finkinfo/base/expat1.info
Labels: bug, new upstream

#786 enblend-enfuse 4.2
  10.9-libcxx/stable/main/finkinfo/graphics/enblend-enfuse.info
  10.9-libcxx/stable/main/finkinfo/graphics/enblend-enfuse.patch
Labels: new upstream

#834 postgresql updates
  10.9-libcxx/stable/main/finkinfo/database/postgresql10.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql10.patch
  10.9-libcxx/stable/main/finkinfo/database/postgresql11.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql11.patch
  10.9-libcxx/stable/main/finkinfo/database/postgresql12.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql12.patch
  10.9-libcxx/stable/main/finkinfo/database/postgresql94.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql95.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql96.info
  10.9-libcxx/stable/main/finkinfo/database/postgresql96.patch
Labels: new upstream

#838 Revert expat1 to bzip2 source
  10.9-libcxx/stable/main/finkinfo/base/expat1.info
Labels: bug

#800 xrootd4: new version
  10.9-libcxx/stable/main/finkinfo/sci/xrootd4.info
  10.9-libcxx/stable/main/finkinfo/sci/xrootd4.patch
Labels: waiting for owner

#799 new libversion of physfs
  10.9-libcxx/stable/main/finkinfo/libs/physfs-shlibs.info
  10.9-libcxx/stable/main/finkinfo/libs/physfs1-shlibs.info
Labels: new upstream, waiting for owner

#801 icon: new version, switch to 64-bit arch
  10.9-libcxx/stable/main/finkinfo/languages/icon.info
  10.9-libcxx/stable/main/finkinfo/languages/icon.patch
Labels: waiting for owner

#742 libaudiofile 0.3.6
  10.9-libcxx/stable/main/finkinfo/libs/libaudiofile1.info
Labels: new upstream
