Repository fink/fink-distributions, pull requests merged in 2022-01, with the labels that each got.

#860 Autogen update
  10.9-libcxx/stable/main/finkinfo/editors/autogen.info
Labels: new upstream

#843 Texlive 2017
  10.9-libcxx/stable/main/finkinfo/text/libkpathsea6.info
  10.9-libcxx/stable/main/finkinfo/text/libkpathsea6.patch
  10.9-libcxx/stable/main/finkinfo/text/ptexenc1.info
  10.9-libcxx/stable/main/finkinfo/text/teckit.info
  10.9-libcxx/stable/main/finkinfo/text/texlive-10.15.info
  10.9-libcxx/stable/main/finkinfo/text/texlive-11.0.info
  10.9-libcxx/stable/main/finkinfo/text/texlive-11.3.info
  10.9-libcxx/stable/main/finkinfo/text/texlive-implicit-declarations.patch
  10.9-libcxx/stable/main/finkinfo/text/texlive-texmf-10.15.info
  10.9-libcxx/stable/main/finkinfo/text/texlive-texmf-11.0.info
  10.9-libcxx/stable/main/finkinfo/text/texlive-texmf-11.3.info
  10.9-libcxx/stable/main/finkinfo/text/texlive-texmf.info
  10.9-libcxx/stable/main/finkinfo/text/texlive-texmf.patch
  10.9-libcxx/stable/main/finkinfo/text/texlive-xdvik-overlay.patch
  10.9-libcxx/stable/main/finkinfo/text/texlive.info
Labels: help wanted, new upstream

#773 e2fsprogs: update to 1.46.2, add testsuite
  10.9-libcxx/stable/main/finkinfo/utils/e2fsprogs.info
  10.9-libcxx/stable/main/finkinfo/utils/e2fsprogs.patch
Labels: new upstream, waiting for owner
