Repository fink/fink-distributions, pull requests merged in 2024-07, with the labels that each got.

#1139 Update astroid info for python versions 3.9 and 3.10
  10.9-libcxx/stable/main/finkinfo/devel/astroid-py.info
Labels: submissions, waiting for owner

#1141 Update pylint for python 3.9 and 3.10
  10.9-libcxx/stable/main/finkinfo/devel/pylint-py.info
Labels: submissions

#1110 Libcurl upgrades
  10.9-libcxx/stable/main/finkinfo/net/libcurl4.info
Labels: help wanted

#1143 First release of s3transfer python module package version 0.10.2
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/s3transfer-py.info
Labels: new package

#1151 New package botocore for AWS services
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/botocore-py.info
Labels: missing (build) dependency, new package

#1153 New package jmespath-py to parse JSON coded text.
  10.9-libcxx/stable/main/finkinfo/libs/pythonmods/jmespath-py.info
Labels: new package
