Repository fink/fink-distributions, pull requests merged in 2024-11, with the labels that each got.

#1168 Update to glib2-shlibs to compile under CLT 16.1 / macOS 15.X
  10.9-libcxx/stable/main/finkinfo/gnome/glib2-shlibs.info
  10.9-libcxx/stable/main/finkinfo/gnome/glib2-shlibs.patch
Labels: bug

#1172 scalar-list-utils-pm updated for perl 5.34.1
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/scalar-list-utils-pm.info
Labels: enhancement

#1166 Update locale-gettext for MacOS 15 / perl 5.34.1
  10.9-libcxx/stable/main/finkinfo/libs/perlmods/locale-gettext-pm.info
Labels: enhancement

#1183 Support arm processor in libtidyp-shlibs
  10.9-libcxx/stable/main/finkinfo/web/libtidyp-shlibs.info
Labels: arm64

#1165 Update to compface face to patch implicit definition as int
  10.9-libcxx/stable/main/finkinfo/graphics/compface.info
  10.9-libcxx/stable/main/finkinfo/graphics/compface.patch
Labels: bug

#1170 blt package update: Merged separate architecture, patched configure file
  10.9-libcxx/stable/main/finkinfo/x11/blt-arm64.info
  10.9-libcxx/stable/main/finkinfo/x11/blt.info
  10.9-libcxx/stable/main/finkinfo/x11/blt.patch
Labels: enhancement
