Repository fink/fink-distributions, pull requests merged in 2025-01, with the labels that each got.

#1209 aquaterm update for Sequoia
  10.9-libcxx/stable/main/finkinfo/graphics/aquaterm.info
Labels: enhancement

#1190 etherape: v0.917
  10.9-libcxx/stable/main/finkinfo/net/etherape.info
  10.9-libcxx/stable/main/finkinfo/net/etherape.patch
Labels: new upstream, waiting for owner

#1158 update libiconv and gettext to latest upstream for building on macOS15
  10.9-libcxx/stable/main/finkinfo/base/dpkg.info
  10.9-libcxx/stable/main/finkinfo/base/gettext-tools-tests.patch
  10.9-libcxx/stable/main/finkinfo/base/gettext-tools.info
  10.9-libcxx/stable/main/finkinfo/base/libgettext8-shlibs.info
  10.9-libcxx/stable/main/finkinfo/base/libgettext8-shlibs.patch
  10.9-libcxx/stable/main/finkinfo/base/libiconv.info
  10.9-libcxx/stable/main/finkinfo/base/libiconv.patch
Labels: new upstream
