Repository fink/fink-distributions, pull requests merged in 2025-04, with the labels that each got.

#1236 Coreutils patch for newer Clang
  10.9-libcxx/stable/main/finkinfo/utils/coreutils.info
Labels: bug

#1233 Creation of librsync2 as update to librsync.
  10.9-libcxx/stable/main/finkinfo/libs/librsync2.info
Labels: new upstream

#1232 Cmake system libs
  10.9-libcxx/stable/main/finkinfo/devel/cmake.info
Labels: submissions
